import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { ThemeProvider } from "next-themes";
import { stackServerApp } from "../stack";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Main from "@/components/Main";
import { useState } from "react";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<StackProvider app={stackServerApp}>
					<StackTheme>
						<ThemeProvider>
							<div className="h-screen overflow-hidden">
								{/* <Navbar /> */}
								<div className="flex">
									<Main>{children}</Main>
								</div>
							</div>
						</ThemeProvider>
					</StackTheme>
				</StackProvider>
			</body>
		</html>
	);
}
